disabled_rules:
  - empty_parentheses_with_trailing_closure
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - redundant_string_enum_value

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - sorted_first_last
  - sorted_imports

excluded:
  - Carthage
  - Pods

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
    mandatory_comma: true
