platform :ios, '11.3'

def common_pods
  pod 'Anchorage'
  pod 'BonMot'
  pod 'Swiftilities/Math'
end

target 'Gud Tay' do
  use_frameworks!

  common_pods

  # Pods for Gud Tay
  pod 'SwiftLint'
  pod 'Sourcery'
  pod 'Alamofire'
  pod 'OHHTTPStubs'
  
  pod 'Swiftilities/Logging'

  target 'Gud TayTests' do
    inherit! :search_paths
    common_pods
  end

  target 'Gud TayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
