disabled_rules:
  - function_body_length
  - line_length
  - empty_parentheses_with_trailing_closure
  - redundant_string_enum_value
  - large_tuple

enabled_rules:
  - vertical_whitespace
  - operator_usage_whitespace

excluded:
  - Carthage
  - Pods
  - Constants

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
    mandatory_comma: true
