disabled_rules:
  - empty_parentheses_with_trailing_closure
  - function_body_length
  - large_tuple
  - line_length
  - redundant_string_enum_value

opt_in_rules:
  - operator_usage_whitespace
  - vertical_whitespace

excluded:
  - Carthage
  - Pods

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
    mandatory_comma: true
