platform :ios, '10.0'

target 'Gud Tay' do
  use_frameworks!

  # Pods for Gud Tay
  pod 'Anchorage', :git => 'git@github.com:Raizlabs/Anchorage.git', :commit => 'c0626ea77907a76a1d0b70e2639a6c78eafcf5d7'
  pod 'SwiftGen'
  pod 'BuddyBuildSDK'
  pod 'BonMot/UIKit'

  target 'Gud TayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Gud TayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
