platform :ios, '10.0'

target 'Gud Tay' do
  use_frameworks!

  # Pods for Gud Tay
  pod 'Anchorage', :git => 'git@github.com:Raizlabs/Anchorage.git', :commit => 'da947d7c8c554de48fb9404a91ea4b26cfb1e7f9'
  pod 'SwiftGen'

  target 'Gud TayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Gud TayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
