platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def shared
  pod 'Anchorage'
  pod 'BonMot'

  pod 'Then'

  pod 'Swiftilities/HairlineView'
  pod 'Swiftilities/Lifecycle'
  pod 'Swiftilities/Logging'
end

target 'GudTay' do
  shared()
end

target 'GudTayTests' do
  shared()
  pod 'OHHTTPStubs/Swift'
  pod 'SnapshotTesting'
end

target 'Services' do
  shared()
end

target 'Utilities' do
end

target 'UtilitiesTests' do
end

pod 'SwiftGen'
pod 'Sourcery'
pod 'SwiftLint'
