platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def shared
  pod 'Swiftilities/HairlineView'
  pod 'Swiftilities/Lifecycle'
  pod 'Swiftilities/Logging'
end

target 'GudTay' do
  shared()
end

target 'GudTayTests' do
  shared()
end

target 'Services' do
  shared()
end

target 'Utilities' do
end

target 'UtilitiesTests' do
end

pod 'SwiftGen'
pod 'SwiftLint'

post_install do | installer |
  # ugh https://github.com/CocoaPods/CocoaPods/issues/9884
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      if configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
        configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
